version: '3.1'

services:

  stats-server:
    build: stats-service/server
    image: stats-service-image
    container_name: stats-service-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - spring_datasource_url=jdbc:postgresql://stats-db:5432/stats-server-db
      - spring.datasource.user=root
      - spring.datasource.password=root
      - TZ=Europe/Moscow

  stats-db:
    image: postgres:14.3-alpine
    container_name: stats-db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats-server-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - TZ=Europe/Moscow

  ewm-service:
    build: ewm-service
    image: ewm-service-image
    container_name: ewm-service-container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - spring_datasource_url=jdbc:postgresql://ewm-db:5432/ewm-server-db
      - stats-server.url=http://stats-server:9090
      - spring.datasource.user=root
      - spring.datasource.password=root
      - TZ=Europe/Moscow

  ewm-db:
    image: postgres:14.3-alpine
    container_name: ewm-db-container
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm-server-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - TZ=Europe/Moscow